[versions]
antlr4 = "4.13.2"
antlr4-runtime = "4.13.2"
gson = "2.13.1"
junit-jupiter = "5.13.3"

[libraries]
antlr4 = { module = "org.antlr:antlr4", version.ref = "antlr4" }
antlr4-runtime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr4-runtime" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
